### ISSUE TITLE
Merge stuff from 0.14 branch

### ISSUE THREAD

**Issue by eed3si9n** [sbt/librarymanagement#10]
Originally reported by @dansanduleac

https://github.com/sbt/sbt/pull/1016
https://github.com/sbt/sbt/pull/1140
https://github.com/sbt/sbt/commit/458fea1f1c5e1d4b96ef338e6eb79ccdb6058e21

**Comment by dwijnand** [comment]
There's also https://github.com/sbt/sbt/compare/wip/old-1.0
