### ISSUE TITLE
Fine tune gigahorse options

### ISSUE THREAD

**Issue by jvican** [sbt/librarymanagement#115]
As of 1.0.0, gigahorse backend is enabled for all the http connections. We should have a look at the defaults in Gigahorse (http://eed3si9n.com/gigahorse/configuration.html) and fine tune them for sbt resolution. At first sight they look sane, but I think that we could optimize a little bit more resolution by tweaking some knobs / experimenting.

**Comment by eed3si9n** [comment]
If someone is interested in this, see also:
https://github.com/sbt/librarymanagement/pull/246
https://github.com/sbt/librarymanagement/pull/278

**Comment by eed3si9n** [comment]
Closing this since we're using Coursier by default.
