### ISSUE TITLE
There should be an alias for sbt.libmanagement.Constant in CrossVersionFunctions

### ISSUE THREAD

**Issue by sjrd** [sbt/librarymanagement#138]
Here: https://github.com/sjrd/scala-js/blob/06a06d2d4d6118c4c66d378687324a366b76d384/sbt-plugin/src/main/scala-sbt-0.13/org/scalajs/sbtplugin/SBTCompat.scala#L25

There are aliases for all kinds of `CrossVersion`s, except `Constant`.

**Comment by dwijnand** [comment]
https://github.com/sbt/librarymanagement/pull/135
