### ISSUE TITLE
InlineConfiguration is renamed to ModuleConfiguration but doesn't extend ModuleSettings

### ISSUE THREAD

**Issue by muuki88** [sbt/librarymanagement#154]
Hi,

While fixing the `SettingsHelper` to be compatible with `1.x` I was confused by the [1.0.0 notes](https://github.com/sbt/librarymanagement/blob/1.x/notes/1.0.0.markdown). It states

> InlineConfiguration is renamed to ModuleConfiguration

In the `0.13.x` `SettingsHelper` I have this line

```scala
moduleSettings := InlineConfiguration(projectID.value, projectInfo.value, Seq.empty)
```

which I tried to turn into

```scala
moduleSettings := ModuleConfiguration(projectID.value, projectInfo.value)
```

The issue was that `ModuleConfiguration` doesn't extend `ModuleSettings`. However `ModuleDescriptorConfiguration` does and seems to work:

```scala
moduleSettings := ModuleDescriptorConfiguration(projectID.value, projectInfo.value)
          .withScalaModuleInfo(scalaModuleInfo.value)
```

I'm not familiar enough with the ivy module implementation details to tell if this is a documentation bug, an implementation bug or if I'm doing something wrong ;)

**Comment by eed3si9n** [comment]
haha. It's a documentation bug.

**Comment by eed3si9n** [comment]
Not sure if this is still relevant. Closing this for now.
