### ISSUE TITLE
Cannot use FileCredentials - xxx not specified in credentials file

### ISSUE THREAD

**Issue by nesc58** [sbt/librarymanagement#161]
Hi,
hope you can help me to understand the following behaviour

When I use sbt I've got a wall of messages like these:
```
[warn] realm not specified in credentials file: C:\Users\<user>\.ivy2\.credentials
[warn] host not specified in credentials file: C:\Users\<user>\.ivy2\.credentials
[warn] user not specified in credentials file: C:\Users\<user>\.ivy2\.credentials
[warn] password not specified in credentials file: C:\Users\<user>\.ivy2\.credentials
```

I am using a file for the credentials
```
credentials += Credentials(Path.userHome / ".ivy2" / ".credentials")
```

.credentials looks like
```
realm=Some Nexus Repository Manager
host=<host>
user=<nexus-user>
password=<nexus-user-pass>
```

I found the following in the code used for sbt 0.13.x and also for 1.x and I ask me:
Which properties will be read? Is there something implicit? 
Line 70 in the Credentials.scala file: https://github.com/sbt/librarymanagement/blob/7b22e78fd94094d2eb888a79602a5240135357b2/ivy/src/main/scala/sbt/librarymanagement/ivy/Credentials.scala#L70-L75

My first thought on this code was: What's about adding / using the `RealmKeys`, `HostKeys` , `UserKeys` and `PasswordKeys` defined a few lines above as properties to read from the file?

Do FileCredentials really work or is something broken with my configuration?
If I use `Credentials("Some Nexus Repository Manager", "<host>", "<nexus-user>", "<nexus-user-pass>")` everything works fine.

Thanks in advance,
Dennis

**Comment by nesc58** [comment]
I found the issue:
The encoding of the .credentials file was `UCS-2 LE BOM`. I change the encoding to UTF-8. Now it works

**Comment by dirspb** [comment]
I had similar issue with LF line break on macOS.

**Comment by henryfw** [comment]
> I had similar issue with LF line break on macOS.

I had to save file in Windows format.
