### ISSUE TITLE
JDK9 Warning: Illegal reflective access 

### ISSUE THREAD

**Issue by d6y** [sbt/librarymanagement#169]
Hello.

I've installed JDK9 (MacOS) and using sbt 1.0.2 (via sbt-extras) I see the following when I start sbt:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by sbt.internal.librarymanagement.ivyint.ErrorMessageAuthenticator$ (file:/Users/richard/.sbt/boot/scala-2.12.3/org.scala-sbt/sbt/1.0.2/librarymanagement-ivy_2.12-1.0.2.jar) to field java.net.Authenticator.theAuthenticator
WARNING: Please consider reporting this to the maintainers of sbt.internal.librarymanagement.ivyint.ErrorMessageAuthenticator$
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

It doesn't cause me any problems but as requested in the output I'm "reporting this to the maintainers" (assuming I've reached the right place!).

Thank you.

**Comment by dwijnand** [comment]
Cheers Richard.

**Comment by Martin-Smith2** [comment]
I have the same problem in windows

**Comment by hiejulia** [comment]
I have the same problem in MacOS as well.

**Comment by AlanBateman** [comment]
It seems to be hacking into a private field in java.net.Authenticator to get the globally configured Authenticator, it should use Authenticator.getDefault() (new API in Java SE 9) instead.

**Comment by dwijnand** [comment]
Fixed in #173.

**Comment by nhooey** [comment]
I have the same error:
```
WARNING: Illegal reflective access by sbt.internal.librarymanagement.ivyint.ErrorMessageAuthenticator$ (file:/Users/${USER}/.sbt/boot/scala-2.12.3/org.scala-sbt/sbt/1.0.2/librarymanagement-ivy_2.12-1.0.2.jar) to field java.net.Authenticator.theAuthenticator
```

Which occurs when I run the tests for my IntelliJ IDEA Scala project. I used `jrudolph/sbt-dependency-graph` to check the dependency tree for the project, and `librarymanagement-ivy` isn't found, but these outdated versions of `librarymanagement-ivy` are downloaded when first building the project:

```
~/.sbt/boot/scala-2.12.3/org.scala-sbt/sbt/1.0.2/librarymanagement-ivy_2.12-1.0.2.jar
~/.sbt/boot/scala-2.12.3/org.scala-sbt/sbt/1.0.2/librarymanagement-core_2.12-1.0.2.jar
```

How do I get SBT to use the updated versions of `librarymanagement-ivy` to avoid the `Illegal reflective access` error?

@dwijnand, @AlanBateman

**Comment by dwijnand** [comment]
change the sbt.version in project/build.properties

**Comment by stephane-segning** [comment]
Which version should we use then ?

**Comment by dwijnand** [comment]
Use https://github.com/sbt/sbt/releases as a reference.

**Comment by PeterLambCSA** [comment]
I upgraded from sbt version 0.13.5  to 0.13.17  in build.properties and I started getting this error. However, if I try to upgrade to a later version of SBT 1.0.0 onwards, then the play plugin refuses to load, so I seem to be stuck with 0.13.17 and suffering the error message as I can't go beyond that version without the play plugin failure. Any ideas?

**Comment by SethTisue** [comment]
@PeterLambCSA that'd be a good question to ask in a Play forum ("what version of Play supports sbt 1?")

**Comment by PeterLambCSA** [comment]
@SethTisue Thanks, Seth. I can't upgrade my Play version right now, so I guess I'll have to just abandon the SBT upgrade.
