### ISSUE TITLE
"Choosing local for com.example#x_2.12;a.b.c-SNAPSHOT" warning

### ISSUE THREAD

**Issue by eed3si9n** [sbt/librarymanagement#172]
## steps

Use SNAPSHOTs in the graph.

## problem

```
[warn] Choosing local for com.example#x_2.12;a.b.c-SNAPSHOT
```

The warning is not really clear, or actionable.

## expectations

Clarify wording to say something like:

```
[warn] Resolving a snapshot version. It's going to be slow unless you use `updateOptions := updateOptions.value.withLatestSnapshots(false)` options.
[info] Out of 2 candidates we found for com.example#x_2.12;a.b.c-SNAPSHOT in local and foo, we are choosing local.
[info] Out of 2 candidates we found for com.example#y_2.12;a.b.c-SNAPSHOT in local and foo, we are choosing local.
```

**Comment by dwijnand** [comment]
Here's the relevant code: https://github.com/sbt/librarymanagement/blob/v1.0.2/ivy/src/main/scala/sbt/internal/librarymanagement/ivyint/SbtChainResolver.scala#L219

I don't like the wording of "It's going to be slow unless", but I'm :+1: on clarifying the messaging.

**Comment by benhutchison** [comment]
206 secs to import a SBT project graph with lots of SNAPSHOT dependencies into Intellj  led me to google "sbt Choosing local SNAPSHOT slow" which led me here. 

I added `updateOptions := updateOptions.value.withLatestSnapshots(false)` and retested a build refresh, took 33s. 

So for me at least, the specific advice would have been useful. Im slowly learning all the SBT switches but`withLatestSnapshots(false)` I didn't know about.

**Comment by eed3si9n** [comment]
@benhutchison Good to know. Should we/you/someone make a PR as my suggested warning, or do you have ideas to improve "it's gonna be slow af unless you do this list of demands" style?

**Comment by benhutchison** [comment]
Im 👍 for your suggested warning, cant think of anything better

**Comment by eed3si9n** [comment]
Fixed in https://github.com/sbt/librarymanagement/pull/248
