### ISSUE TITLE
URLHandlerRegistry conflict with fm-sbt-s3-resolver plugin in SBT 1.0

### ISSUE THREAD

**Issue by tpunder** [sbt/librarymanagement#175]
I'm trying to track down why fm-sbt-s3-resolver publishing is broken in SBT 1.0: https://github.com/frugalmechanic/fm-sbt-s3-resolver/issues/38

It seems that my `URLHandlerRegistry.setDefault` call:

https://github.com/frugalmechanic/fm-sbt-s3-resolver/blob/ab0188fd3439ee0346c173efae8b4ca462cbea2e/src/main/scala/fm/sbt/S3ResolverPlugin.scala#L98-L113

might be getting wiped out by a `URLHandlerRegistry.setDefault` call here: 

https://github.com/sbt/librarymanagement/blob/480a1a366ddd69e4179fb097eb84163a1ffbf42f/ivy/src/main/scala/sbt/internal/librarymanagement/Ivy.scala#L91-L92

~Does this seem plausible?~ I've verified this is the problem.

**Comment by joan38** [comment]
Any news on this issue?

**Comment by Voltir** [comment]
+1 on this issue - rolling back to 0.13.16 fixed the problem for me

**Comment by jameskoch2** [comment]
I'd love to see a better hook for customizing the URLHandlerRegistry. I'd love to be able to use this to inject kerberos support, but at the moment I can't be confident a custom URLHandler won't get hosed and so am creating a full custom resolver to improve isolation.

**Comment by joan38** [comment]
This is regretion in SBT 1.0 as we see in https://github.com/frugalmechanic/fm-sbt-s3-resolver/issues/38

**Comment by edrevo** [comment]
Any update on this? This issue has a lot of thumbs up 😞

**Comment by joan38** [comment]
Still no news on this? This is invalidating the project https://github.com/frugalmechanic/fm-sbt-s3-resolver ...
I'm also happy to help if needed.

**Comment by dwijnand** [comment]
Hey. I've created https://github.com/sbt/sbt/issues/3758 to help track this issue. I've added it to the 1.0.5 milestone, and I hope it can be fixed by then.

If you, @joan38, or anyone wants to help by investigating what the underlying issue is, what possible solutions there might be, and/or submitting a fixing PR that would be great.

Unfortunately I don't have any real information regarding this issue in particular to give at this time.

**Comment by joan38** [comment]
Thanks @dwijnand for the update and info!

**Comment by tpunder** [comment]
Here is what I'm playing with for fixing this:  https://github.com/sbt/librarymanagement/pull/183

**Comment by tpunder** [comment]
https://github.com/sbt/librarymanagement/pull/183 fixes the problem for me.

**Comment by tpunder** [comment]
This is resolved with SBT 1.0.4!  Thanks!
