### ISSUE TITLE
NullPointerException in GigahorseUrlHandler : 54 (Content Type null)

### ISSUE THREAD

**Issue by TeofilisMartisius** [sbt/librarymanagement#180]
Hi,

SBT version 1.0.2.

I'm getting NullPointerExceptions in GigahorseUrlHandler.scala line 54:

```
            BasicURLHandler.getCharSetFromContentType(response.body().contentType().toString)
```

It assumes that content type will ALWAYS be present. However, when performing HEAD requests, okhttp does NOT give content Type information, contentType is null. To try it, you can run this to verify:

```
import java.net.URL
import okhttp3.{OkHttpClient, Request}

object test {
  def main(args: Array[String]) = {
    val okHttpClient = new OkHttpClient()

    val url = new URL("http://your.url.com/");

    val head = new Request.Builder().url(url).head()
    val responseHead = okHttpClient.newCall(head.build()).execute()
    // Will be null
    println("Content Type for HEAD =" + responseHead.body().contentType())

    val get = new Request.Builder().url(url).get()
    val responseGet = okHttpClient.newCall(get.build()).execute()
    println("Content Type for GET =" + responseGet.body().contentType())
  }
}
```

Sincerely,
Teofilis Martisius

**Comment by TeofilisMartisius** [comment]
Ok, that's not the case for all URLs, only for some. I have JFrog artifactory that for some reason produces NULL content type for HEAD requests for some directory listings. 

I found some URLs on that artifactory that do return "Content-Type:" header for GET requests, and do NOT return it for HEAD requests. So the server isn't behaving correctly.

However, I still maintain this is a bug in SBT/Ivy and it should be fixed. There WILL be broken servers on the internet, and that should not result in NullPointerExceptions. 

Is there a way to force GET request to be always used? There is some Ivy setting (httpRequestMethod), but I'm struggling to apply it inside SBT.

**Comment by dhoepelman** [comment]
We encountered the same problem with the osgeo Geotools repository (e.g. [this pom](https://download.osgeo.org/webdav/geotools/org/geotools/gt-api/18.2/gt-api-18.2.pom)), so there definitely are servers in the wild that don't return a content-type for `.pom` files.

**Comment by igorlev** [comment]
I'm running into this issue with the geotools repo as well. Any thoughts on releasing the merged PR (#214) as part of 1.1.4 (or later versions)?

**Comment by dwijnand** [comment]
yep it'll ship in sbt 1.2.0

**Comment by eed3si9n** [comment]
https://github.com/sbt/librarymanagement/pull/214 went into 1.1.x so it will be part of 1.1.2 hopefully that will come out soon.
