### ISSUE TITLE
lm is broken in 1.1.x

### ISSUE THREAD

**Issue by cunei** [sbt/librarymanagement#219]
lm 1.1.x is currently broken.

It was fine in https://github.com/sbt/librarymanagement/commit/4c5e1b926b1a992b273478a55e350a56bde57e19, failed in https://github.com/sbt/librarymanagement/commit/67d97fed250a7b63b51eee3b5ca62ef275c93d6a.

The commits that intervened in between are here: https://github.com/sbt/librarymanagement/compare/4c5e1b926b1a992b273478a55e350a56bde57e19...67d97fed250a7b63b51eee3b5ca62ef275c93d6a

The error message when calling `lmCore/packageSrc` is:
```
[info] Packaging /home/cunei/activities/clones/librarymanagement/core/target/scala-2.12/librarymanagement-core_2.12-1.1.3-sources.jar ...
[error] java.util.zip.ZipException: duplicate entry: sbt/librarymanagement/MakePomConfiguration.scala
[error] 	at java.util.zip.ZipOutputStream.putNextEntry(ZipOutputStream.java:232)
[error] 	at java.util.jar.JarOutputStream.putNextEntry(JarOutputStream.java:109)
[error] 	at sbt.io.IO$.addFileEntry$1(IO.scala:550)
[error] 	at sbt.io.IO$.$anonfun$writeZip$3(IO.scala:559)
[error] 	at sbt.io.IO$.$anonfun$writeZip$3$adapted(IO.scala:559)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:929)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:929)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[error] 	at sbt.io.IO$.writeZip(IO.scala:559)
[error] 	at sbt.io.IO$.$anonfun$archive$1(IO.scala:513)
[error] 	at sbt.io.IO$.$anonfun$archive$1$adapted(IO.scala:510)
[error] 	at sbt.io.IO$.$anonfun$withZipOutput$1(IO.scala:595)
[error] 	at sbt.io.IO$.$anonfun$withZipOutput$1$adapted(IO.scala:584)
[error] 	at sbt.io.Using.apply(Using.scala:22)
[error] 	at sbt.io.IO$.withZipOutput(IO.scala:584)
[error] 	at sbt.io.IO$.archive(IO.scala:510)
[error] 	at sbt.io.IO$.jar(IO.scala:489)
[error] 	at sbt.Package$.makeJar(Package.scala:121)
...
```

**Comment by cunei** [comment]
It seems an auto-generated contraband file collides with an identically named file in the regular source tree:
```
./core/src/main/contraband-scala/sbt/librarymanagement/MakePomConfiguration.scala
./core/src/main/scala/sbt/librarymanagement/MakePomConfiguration.scala
```
Renaming the latter to something else, for instance `MakePomConfigurationFunctions.scala`, solves the issue.

**Comment by dwijnand** [comment]
https://github.com/sbt/librarymanagement/pull/62/commits/e209499544d01edb8fb3fa8da43dc6bf09ad8fbb again.. we should enforce this

**Comment by eed3si9n** [comment]
We don't catch them locally because we don't build source jars?

**Comment by dwijnand** [comment]
sometimes I don't even compile the code and just see what Travis CI thinks of my PR (on the first iteration).

anyways, let's CI enforce this: https://github.com/sbt/librarymanagement/pull/225.
