### ISSUE TITLE
"Comparing unrelated types: String and ConfigRef" in CachedResolutionResolveEngine.scala

### ISSUE THREAD

**Issue by xuwei-k** [sbt/librarymanagement#259]
https://github.com/sbt/librarymanagement/blob/3fcc9e3629a329ed554e43d93a86de5ba3ad0242/ivy/src/main/scala/sbt/internal/librarymanagement/ivyint/CachedResolutionResolveEngine.scala#L971

<img width="681" alt="screen shot 2018-08-02 at 0 42 21" src="https://user-images.githubusercontent.com/389787/43532463-1b007ade-95ed-11e8-90c7-218ea642ca4d.png">

**Comment by eed3si9n** [comment]
Gaa contains hits me again. Thank you Yoshida san.
