### ISSUE TITLE
Tests jar are no longer published on maven

### ISSUE THREAD

**Issue by Xephi** [sbt/librarymanagement#275]
Since librarymanagement 1.0.X, you do not publish any tests jar artifact on maven repositories

I used to extend some spec for unitary tests when i used librarymanagement 0.1.X 
you can take a look into :  https://repo1.maven.org/maven2/org/scala-sbt/librarymanagement_2.10/0.1.0-M9/ , which have tests jar published

And now :  https://repo1.maven.org/maven2/org/scala-sbt/librarymanagement-core_2.12/1.2.2/ tests jar are no longer published

Thanks for your help

**Comment by eed3si9n** [comment]
I don't intend to maintain our internal tests as library, so I don't think it makes sense to publish test JARs. It's opensource, so feel free to copy paste our code under Apache v2 license.
