### ISSUE TITLE
Clarify licensing

### ISSUE THREAD

**Issue by roptat** [sbt/librarymanagement#283]
Hi,

I'd like to package sbt-librarymanagement in my distro (as a dependency of sbt). We only package free software, and you don't seem to declare a license. I have seen the NOTICE file in the core directory, so I assume the source present in that directory is under the ASL 2.0 license.

I'm not sure if I need them yet, but none of the other directories declare a license. There doesn't seem to be a license declaration in source files either. As such, I can only assume the rest of this repository is non-free by default. Could you clarify the terms of the license for building, using and distributing the rest of this repo?

Thank you!

**Comment by eed3si9n** [comment]
We'll try to sort this out, but basically 1.2.x series is BSD New as stated on the POM file - https://repo1.maven.org/maven2/org/scala-sbt/librarymanagement-core_2.12/1.2.3/librarymanagement-core_2.12-1.2.3.pom

In 1.3.x we will switch to Apache 2.0.

**Comment by roptat** [comment]
Thank you for your quick answer! Could you add a LICENSE file or similar at the top-level of the repository?
