### ISSUE TITLE
Requests for nonexistent jar artifacts when packaging is pom

### ISSUE THREAD

**Issue by LogicalTime** [sbt/librarymanagement#293]
When working behind proxies trying to resolve artifacts that do not exist can slow things down unbearably. Currently SBT v1.2.8 seems to request jar artifacts when the pom.xml says packaging=pom. So resolution can stall out for minutes trying to fetch jar files that the pom indicates are not there. Can we please fix this, or have a property that toggles it so SBT can be more widely adopted?

**Comment by eed3si9n** [comment]
I'm folding this request into https://github.com/sbt/sbt/issues/4531
