### ISSUE TITLE
jsch and being intransitive

### ISSUE THREAD

**Issue by dwijnand** [sbt/librarymanagement#68]
We're currently getting the following warning:

```
[warn] Found intransitive dependency (com.jcraft:jsch:0.1.46) while publishMavenStyle is true, but Maven repositories
[warn]   do not support intransitive dependencies. Use exclusions instead so transitive dependencies
[warn]   will be correctly excluded in dependent projects.
```

I don't know the history here. Looks like jsch's only (non-test) dependency is:

```xml
<dependency>
  <groupId>com.jcraft</groupId>
  <artifactId>jzlib</artifactId>
  <version>1.0.7</version>
  <optional>true</optional>
</dependency>
```

We're now configuring sbt (modules) to publish to Maven, so it looks like we have to change how we do the same thing. Except it's not clear to me how exactly to transform `intranstive()` by "using exclusions".

**Comment by dwijnand** [comment]
Thoughts:

* it's possible jsch once had dependencies that were problematic, but the version we're using now (0.1.46) doesn't

* it's possible that `intransitive()` was a workaround for `<optional>true</optional>` not being respected, so all we need to do is just remove `intranstive()`.

**Comment by eed3si9n** [comment]
https://github.com/sbt/sbt-zero-seven/commit/b157882f9d5e0775e1fc062deadf4e65ba046f5c added Jsch 0.1.31 in 2009. The dependency looks the same then - https://repo1.maven.org/maven2/com/jcraft/jsch/0.1.31/jsch-0.1.31.pom

Let's remove the intransitive.

**Comment by dwijnand** [comment]
I think the 'intransitive' derives from the `transitive="false"` in https://github.com/sbt/sbt-zero-seven/commit/ee36c5ee4ee259b9a229e3af2631d8e008d3856e - which has no explanation.
