### ISSUE TITLE
matching method is inaccessible from build.sbt

### ISSUE THREAD

**Issue by eed3si9n** [sbt/librarymanagement#83]
Ref https://github.com/sbt/librarymanagement/pull/78
`matching` became `private[sbt]`, so it's no longer accessible. Prior to the change at least we could get to it via importing internal.

**Comment by dwijnand** [comment]
Ah, the use case suffering from this change is our own scripted tests..

Given the use case is so niche, how do you feel about us finding a call-site workaround, by defining a forwarder in a project/*.Scala util, rather than messing with the encoding here?

**Comment by eed3si9n** [comment]
Since there there are a bunch tests that use it, I think we should just expose it (and any other enrichment that looks safe) out since we're doing it for one method.

**Comment by dwijnand** [comment]
Without intending to sound facetious, do you have criteria (or a rule of thumb) for what you consider to be safe?

**Comment by eed3si9n** [comment]
Something that has concrete meaning and won't change as we might add fields in the future would be relatively safe, I think.
