### ISSUE TITLE
Client-side redirection

### ISSUE THREAD

**Issue by eed3si9n** [sbt/librarymanagement#89]
Instead of relying on repo.(typesafe | scala-sbt).org there should be a mechanism to do redirection on client-side.

Ref https://github.com/sbt/sbt/issues/2189

**Comment by jvican** [comment]
The gitter discussion: https://gitter.im/sbt/sbt-contrib?at=59011219881b89e1018c16dc.

**Comment by eed3si9n** [comment]
This would involve us defining and putting a redirect rule file publicly on `repo.typesafe.com` etc.
